# Geef me alle cspec:Activiteit, cspec:Object en cspec:Functie die beschikbaar zijn binnen de collectieve PCB sets

PREFIX cspec: <http://ontologie.crow.nl/bibliotheekspecificatie/201711/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cdoc: <http://ontologie.crow.nl/document/201711/>

select ?onderwerpURI ?onderwerpCode ?onderwerpNaam ?onderwerpType ?collectieNaam ?datasetNaam
where { 
    VALUES ?onderwerpType { cspec:Object cspec:Activiteit cspec:Functie} 
    ?onderwerpURI rdf:type ?onderwerpType ;
                  cspec:naam ?onderwerpNaam .

    FILTER regex(str(?onderwerpURI), "/ns/PCB")

	OPTIONAL {?onderwerpURI cspec:code ?onderwerpCode }.
    
    OPTIONAL {?onderwerpURI cspec:isLidVan ?collectieURI .
    		  ?collectieURI cspec:naam ?collectieNaam .}
    OPTIONAL {?onderwerpURI cspec:hoortBijDataset ?datasetURI .
              ?datasetURI cspec:naam ?datasetNaam .}
}