PREFIX skos: 	<http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: 	<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dc:		<http://purl.org/dc/terms/>
PREFIX crow:	<http://www.crowprocontractdata.nl/ns/crow/2015/05/specificatie-schema/>
# PREFIX utrecht: <http://linkeddata.crow.nl/publication/ns/utrecht/2016/11/04/specs/>

SELECT DISTINCT ?EisId ?EisNaam ?EisTekst ?ObjNaam ?ObjCod ?VerNaam ?MethNaam
WHERE
{ 
    BIND ("{{&aft}}" AS ?aft)

	?eisId 	
			rdf:type crow:Eis ;
			skos:prefLabel ?EisNaam ;
			crow:eisTekst ?EisTekst ;
			crow:specificeert ?ObjId ; # Het object waar de eis bij hoort
			crow:heeftVerificatie ?VerId ;
	.
	{{&filEis}}
	
	?ObjId
			skos:prefLabel ?ObjNaam ; # De typenaam van het object
			dc:identifier ?ObjCod ; # De type-code van het object
	.
	{{&filObj}}
	
	?VerId
			skos:prefLabel ?VerNaam ; # De verificatie-naam
			# skos:definition ?VerDef ;
			crow:verificatiemethode ?MethId ;
	.
	{{&filVer}}
	
	?MethId	skos:prefLabel ?MethNaam ; # De verificatiemethode-naam
	.
	
    BIND ( IF(CONTAINS(str(?eisId), ?aft), strafter(str(?eisId), ?aft), str(?eisId)) as ?EisId)
}