# CROW-IMBOR (2020-08)
# Geef me alle Eigenschappen van een Beheerobject [filNam] (inclusief overerving) 
# rdfs:subClassOf* werkt niet op het CROW LDP. Vandaar dat we deze manuele UNION moeten uitvoeren.
# Getest tegen: http://linkeddata.crow.nl/publication-v2/contexts/cpc/

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX nta8035: <https://w3id.org/def/basicsemantics-owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX groep: <http://linkeddata.crow.nl/publication-v2/ns/crow/imbor/def/groepering/>

SELECT ?FysiekObjectURI ?FysiekObjectLabel ?EigenschapURI ?EigenschapLabel ?EigenschapVanObjectLabel ?Versie

WHERE {

# Het kan zijn dat dit aangepast moet worden naar subClassOf nta8035:PhysicalObject
            ?FysiekObjectURI skos:prefLabel ?preflabel .

 # ... en die voorkomen in deze versie ...
    groep:Versie2020-08 skos:member ?FysiekObjectURI ;
            rdfs:label ?Versie .
 # ... filter op de juiste URI (dus niet met /version/ er in)...
     FILTER (!CONTAINS(str(?EigenschapURI), "/version/" )) 
   
# ... met deze parameter.

            FILTER (LCASE(str(?preflabel)) = "{{&filNam}}") # heel woord
            #FILTER (CONTAINS(?preflabel, "{{&filNam}}")) # gedeelte
            BIND (?preflabel AS ?FysiekObjectLabel)
            
# Trek het property-path uit elkaar om de superklasse te laten zien en gebruik de "UNION" hack om de property path bug in het CROW LDP te omzeilen.
# rdfs:subClassOf* werkt niet op het CROW LDP. Vandaar dat we deze manuele UNION moeten uitvoeren.
            {
              ?FysiekObjectURI rdfs:subClassOf [
                  rdfs:subClassOf [
                    rdfs:subClassOf [
                      rdfs:subClassOf [
                        rdfs:subClassOf [
                          rdfs:subClassOf [
                            rdfs:subClassOf ?SuperKlasse
                          ]
                        ]
                      ]
                    ]
                  ]
                ] .
            } UNION {
              ?FysiekObjectURI rdfs:subClassOf [
                  rdfs:subClassOf [
                    rdfs:subClassOf [
                      rdfs:subClassOf [
                        rdfs:subClassOf [
                          rdfs:subClassOf ?SuperKlasse
                        ]
                      ]
                    ]
                  ]
                ] .
            } UNION {
              ?FysiekObjectURI rdfs:subClassOf [
                  rdfs:subClassOf [
                    rdfs:subClassOf [
                      rdfs:subClassOf [
                        rdfs:subClassOf ?SuperKlasse
                      ]
                    ]
                  ]
                ] .
            } UNION {
              ?FysiekObjectURI rdfs:subClassOf [
                  rdfs:subClassOf [
                    rdfs:subClassOf [
                      rdfs:subClassOf ?SuperKlasse
                    ]
                  ]
                ] .
            } UNION {
              ?FysiekObjectURI rdfs:subClassOf [
                  rdfs:subClassOf [
                    rdfs:subClassOf ?SuperKlasse
                  ]
                ] .
            } UNION {
              ?FysiekObjectURI rdfs:subClassOf [
                  rdfs:subClassOf ?SuperKlasse 
                ] .
            } UNION {
              ?FysiekObjectURI rdfs:subClassOf ?SuperKlasse .
            } UNION {
              ?SuperKlasse skos:prefLabel ?FysiekObjectLabel .
            }

            ?SuperKlasse skos:prefLabel ?EigenschapVanObjectLabel .
            
            ?SHACLNodeShape sh:targetClass ?SuperKlasse .
            ?SHACLNodeShape sh:property ?SHACLPropertyShape .

# Laat de relatie zien van de SHACL Shape, naar de eigenschap (inclusief via de blanknodes)...
            { ?SHACLPropertyShape sh:path/(rdf:first) ?EigenschapURI .}
    UNION   { ?SHACLPropertyShape sh:path ?EigenschapURI .}
            ?EigenschapURI skos:prefLabel ?EigenschapLabel .

# ... en filter de hasPart relaties eruit om alleen echte eigenschappen te zien.
            MINUS { ?SHACLPropertyShape sh:path nta8035:hasPart }
    
}

ORDER BY str(?FysiekObjectLabel) str(?EigenschapLabel) str(?EigenschapVanObjectLabel)
