name: Copy all queries from subdirs/ to all/

on: push

jobs:
  copy_to_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Copy files
        shell: bash
        run: |
          rm -f src/all/*.rq
          find src/ -name "*.rq" -not -path "src/all/**" -exec cp {} src/all \;

      - name: Commit changes
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "Copy queries to src/all"
          git push
